language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

install:
  - curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash

before_script:
  - /bin/echo "${ACCOUNT_KEY}" | /usr/local/bin/parse configure accountkey -d

script:
#  - /usr/local/bin/parse deploy -f

env:
  global:
    secure: lIRb4dE457+JQMvMJGEw94WQYTFtGM6nCmjZQCO++AjCBIHnPWpSikd5usHVSxx1dypO8mKo7YFmrlMl+Zccb4aTXaI29mLSIteflGS1tHt1GvqzkBM22MiKPQYUtCAxU6g4EuHxTYMUYF+fV/USPEsiqQ6lLZ9RI7J7LXrxKuBUtAjHADG3iwSPmMEeWsWPrJGy+85/ozvhZ6WIsK/HPJgEBYj1qfQqpWJTbEd0kSjiDB+bt85b0ILN23StgXwdbNGeW/lRzhW34+e4yJrugNcTqNvHXT2/u8oqxpqfRdvdQu7iipHWuQZVTxgoAeh42ffzFr8htUpS6InYXJkMN4Zi5h0gaUN6V+bOLTs228nqX5IBe++HqMGmyd26Hjimk9SG3nvLgTX2Z5O2rXYIb34YPhtMQBr/kc/nVtG6HqJ3MmpUO46ymQlXE+0y5OLQdOtcwJkj8pR957Y6JNboTthKT+VAa130QPUIRlw7yfJ/9YhAg0x6X1GBzC1NHOVVgg4s8mH/IEcop63R0TMIEEO+4uMEdoR812eZFu9/P4bnAocF6oYxsJJ/zMW/QecwJnnQMWcM1UZd/RTgQHDbRghuznfoYWarGM0w2qCSQrmPEs3At9EmHw1tXkC+gODQgcoBsZP6AwWlOGlZKrVi77cl5fzB1UdoPHFsvLNopq0=
